import { dic31, dic31_2, ene1, ene2, ene2_2, ene3, ene4, ene4_2, ene5, ene5_2 } from "./assets";
import { NavBar, Hero, Divider, Day } from "./components";
import Footer from "./components/Footer";
import TodayButton from "./components/TodayButton";
import styles from "./style";

const App = () => {

  return (
    <div className="w-full overflow-hidden ">
      <div className="fixed sm:bottom-8 bottom-4 sm:right-8 right-2">
        <TodayButton />
      </div>
      <div className={`${styles.flexCenter} z-50`}>
        <NavBar />
      </div>

      <div className={`bg-secondary ${styles.flexStart}} z-0`}>
        <div className={`${styles.boxWidth}`}>
          <Hero />
        </div>
      </div>
      <Divider text={"2022"} bgColor="bg-primary" />
      <Day bgColor="bg-third" name="DIC3122" day="Dic. 31, 2022"
        title="Se va un 2022 muy bonito..."
        paragraphs={[[{ text: "Holaaaa,", underlined: true }], [{ text: "La verdad es que es muchísimo lo que puedo decir de este año. Sin lugar a dudas has sido una bendición gigantesca para mi vida, has llegado a cambiarlo todo y siempre estaré agradecido con Dios por permitirnos coincidir y ser parte de una historia tan bonita como la nuestra. ", }], [{ text: "A pesar de nosotros, Dios ha sido bueno y estoy feliz por el lugar en el que nos encontramos hoy en día. ", marked: true }], [{ text: "Hoy termina un a;o de mucho aprendizaje, de momentos buenos y momentos malos, de muchas risas y muchas lágrimas. Deseo con todo el corazón que te quedes tanto con lo bueno como con lo malo. Lo bueno para recordar momentos felices que viviste, y lo malo para recordar que a pesar de todo no estamos solos y que al final del día..." }], [{ text: "Todo estará bien :)", marked: true }], [{ text: "Has sido lo más bonito de mi 2022; el impacto que has generado en mi vida es inmesurable, y espero de todo corazón que de tu parte exista un sentimiento similar hacia mi. Te quiero tantisimo e intento aportar tanto a tu vida como tu lo haces conmigo." }], [{ text: "Me quedo contigo hasta el día que Dios me lo permita, y hasta ese día, usaré todos los medios posibles (como este) para hacerte saber que te llevo en el fondo de mi corazón siempre, en donde quiera que esté." }], [{ text: "Espero que en tu 2023 puedas...", marked: true }], [{ text: "1. Vivir en una misión, con un propósito que honre y agrade a Dios. Acercarte cada vez más a Él.", underlined: true }], [{ text: "2. Lograr todas tus metas académicas, profesionales y personales." }], [{ text: "3. Conocer a personas que te hagan bien y te quieran mucho :)", underlined: true }], [{ text: "4. Bendecir a muchas personas con todo tu amor y tu talento." }], [{ text: "5. Disfrutar a tus seres queridos al máximo; que vivas con ellos momentos inolvidables.", underlined: true }], [{ text: "6. Vivir experiencias llenas de aprendizaje que te permitan crecer y desarrollarte en todos los aspectos de tu vida." }], [{ text: "7. Amar y ser amada de la manera más bonita posible.", underlined: true }], [{ text: "8. Cumplir absolutamente todo lo que te propongas. Que tus sueños se hagan realidad :)" }], [{ text: "Cuentas conmigo para todo, siempre, bonita.", marked: true }], [{ text: "Si es que me lo permites, me gustaría caminar contigo este 2023. Somos un equipo muy bonito :) y...." }], [{ text: "¡A tu lado todo es mejor!", underlined: true }], [{ text: "Feliz fin de año y pròspero año nuevo a mi solecito que tanto quiero. Nos vemos pronto, bonita.", marked: true }], [{ text: "Un par de fotos bonitas de este año. Solo 2 por que tengo como 1000 favoritas jejeje" }],]}
        images={[dic31, dic31_2]} />
      <Divider text={"2023"} bgColor="bg-primary" />
      <Day bgColor="bg-fourth" name="ENE0123" day="Ene. 01, 2023"
        title="Llega un 2023 de nuevas experiencias..."
        paragraphs={[[{ text: "Holi,", underlined: true }], [{ text: "Hoy empieza un nuevo año, un nuevo ciclo en tu vida, y estoy muuuuuuy emocionado de poder ser parte de.", underlined: true }], [{ text: "Hoy te encuentras ente una nueva oportunidad de cambiar auqellos hábitos que pudieras llegar a considerar 'malos', y comenzar a trabajar en hábitos sanos que te permitan cumplir los objetivos que has definido para este 2023. " }], [{ text: "Estoy bastante expectante por lo que viene y sé que tu también. Sé que lo que Dios tiene preparado para nosotros es algo muy bonito y ansío poder experimentarlo día tras día a lo largo del año. ", marked: true }], [{ text: "Por lo pronto, vayamos un día a la vez, buscando hacer siempre el bien y merjoar en la medida de lo posible. Trabajar en nuestra relación con Él y en el propósito que tiene para nosotros. " }], [{ text: "Estoy muy emocionado por este plan que hemos empezado hoy, espero podamos llevarlo a cabo de inicio a fin. Que el interés individual por conocer de Dios siga creciendo y que podamos ser de apoyo para el crecimiento del otro.", underlined: true }], [{ text: "Espero poder contribuir a la formación de este buen hábito en tí y que cada día busquemos aprender de su palabra de manera individual y en conjunto. " }], [{ text: "Cierro este día mencionando que en mi encontrarás a alguien con quien compartir, meditar, reflexionar y profundizar en lo que vayamos leyendo día con día.", underlined: true }], [{ text: "Adjunto captura de este compromiso que hacemos hoy cada consigo mismo y con Dios, y que compartiremos durante los próximos 365 días, y muchos más, si Dios quiere." }], [{ text: "Te quiero tanto, bonita :)", marked: true }], [{ text: "Hoy en mi oración...", }], [{ text: "Le pido a Dios que te cuide, que te permita reflexionar en lo que escuchaste y aprendiste en el día por medio de las prédicas y las lecturas. Le pido que tu salpullido se vaya reduciendo con el tiempo y que te permita controlar la reacción de mejor manera. Le ruegome permita aportar a reducir tus niveles de estrés en el futuro, y que estés bien en cuestión de salud. También, pido que pronto llegue una oportunidad de trabajo que se acomode a tus tiempos y posibilidades. Que te permita desenvolverte en el ámbito profesional y que con quienes convivas se den cuenta de lo talentosa y valiosa que eres. Agradezco infinitamente por tu vida y ruego por que Dios te de muchos muchos muchos más días aquí en la Tierra.", underlined: true }]]}
        images={[ene1]} />
      <Day bgColor="bg-third" name="ENE0223" day="Ene. 02, 2023"
        reverse={true}
        title="Te quiero tantísimo, mi cielo ♥. "
        paragraphs={[[{ text: "Holi,", underlined: true }], [{ text: "Hoy fue un día muy tranquilo. Estoy muy feliz porque cada vez falta menos para verte de nuevo, si Dios quiere. " }], [{ text: "Te cuento que he estado leyendo un par de planes sobre como podemos 'salir' de una manera sana que agrade a Dios y hoy terminé algunos de ellos. ", }], [{ text: "Si te soy muy sincero, me emociona que nuestra química sea tanta, y me agrada muchísimo que nos encontremos en un punto estiritual muy parecido en nuestras vidas y en nuestra relación con DIos. ", marked: true }], [{ text: "Como leímos, en un inicio Dios creó a Adán y a Eva y, a pesar de su condición de pureza, cometieron el error más grande en la historia del mundo: trajeron la muerte y el pecado." }], [{ text: "Hoy en día nuestra situación es diferente, nacimos pecadores y nuestra naturaleza es y seguirá siendo pecaminosa. No obstante, ahora por la gracia de Dios somos salvos.", underlined: true }], [{ text: "Anhelo con mi corazón que nuestra relación sea para bien, que se note en nuestro trato, nuestra manera de hablar y en todo lo que hagamos que Dios está con nosotros.", }], [{ text: "'Seamos plantitas que dan frutos' :)", marked: true }], [{ text: "Se termina el d[ia y lo único que puedo decir es que, te quiero tanto tanto tanto y quiero ser un arbolito conrigo, mibida ♥.", underlined: true }], [{ text: "Con mucho amor, Jorge V." }], [{ text: "PD: Amé tu nota en sobremanera, por eso la pongo junto con un versículo que leí en la mañana. Te adoro, estrelita.", marked: true }],]}
        images={[ene2_2, ene2]} />
      <Day bgColor="bg-secondary" name="ENE0323" day="Ene. 03, 2023"
        reverse={true}
        title="Gracias por tu apoyo incondicional ♥"
        paragraphs={[[{ text: "Holi,", underlined: true }], [{ text: "Hoy no fue mi mejor día, creo que ha sido un momento complicado y honestamente no me siento al 100%" }], [{ text: "Sin embargo, quiero aprovechar este espacio para agredecerte el apoyo que siempre tienes hacia mí. Quiero que sepas que de verdad lo valoro mucho y te lo agradezco de todo corazón.", marked: true }], [{ text: "Gracias por estar, escuchar, y apoyar en los momentos difíciles. " }], [{ text: "Quiero que sepas que existe de mi parte una intención muy grande de servirte de apoyo en esos momentos en los que no te sientas al 100%, cuando el panorama se ponga complicado. " }], [{ text: "Aunque tu acercamiento sea primero con Dios, apoyo incondicional encuentras en mi, preciosa.", underlined: true }], [{ text: "Te quiero mucho y te abrazo a la distancia para evitar llorar de más.", }], [{ text: "Te quiero muchísimo, desde el fondo de mi corazón.", marked: true }], [{ text: "PD: Canción bonita para los momento difíciles. ", underlined: true }]]}
        images={[ene3]} />
      <Day bgColor="bg-third" name="ENE0423" day="Ene. 04, 2023"
        reverse={false}
        title="Amigos con propósito: una etapa a la vez ♥"
        paragraphs={[[{ text: "Holi,", underlined: true }], [{ text: "Quiero decirte que me encantas como no tienes idea, de verdaaaaaaad.", marked: true }], [{ text: "No puedo creer lo increible que eres en todos los aspectos, eres ese alguien por quien vale la pena ir más allá de lo ordinario, ese alguien que te cambia la vida, ese alguien que no tiene comparación." }], [{ text: "Me hace muy feliz el saber que de nuestra amistad esté surgiendo algo tan bonito y con mucho potencial, algo que busca agradar a Dios. ", marked: true }], [{ text: "Es muy bonito que hablemos el mismo idioma :). De verdad es muy dificil encontrar a alguien que te entienda tanto, y soy feliz de haberlo encontrado en mi mejor amix, en mi bestie." }], [{ text: "Como lo leí hoy en uno de los devocionales, es importante comprender el concepto de amigos con propósito. Me alegra muuuuuuucho saber que ambos estamos preparándonos y formándonos con un buen sustento.", underlined: true }], [{ text: "Quiero decirte que a pesar de que mi ilusión y plan a futuro contigo pasan por mi cabeza constantemente, sé que no debo procuparme tanto por eso ahora, sé que Dios en su momento nos mostrará lo que tiene preparado para nosotros. Por lo pronto, vayamos un día a la vez, una etapa a la vez. Seamos y disfrutemonos siendo amigos con propósito. Querámonos y sigamos creciendo, preparándonos para cuando llegue el momento de pasar a la siguiente etapa, si es que eso está en la voluntad de Dios. ", }], [{ text: "Te quiero muchísimo, niña bonita.", marked: true }], [{ text: "Disfruté mucho hacer FaceTime contigo, hoy (triste por que la foto que tomé no se guardo :c). Me emociona saber que pronto podremos vernos de nuevo, si Dios quiere. Y más emocionado de saber que mi mamá puede llegar a conocerte en unos días. ", underlined: true }], [{ text: "Con amor, Jorge V. ♥", marked: true }],]}
        images={[ene4_2, ene4]} />
      <Day bgColor="bg-fourth" name="today" day="Ene. 05, 2023"
        reverse={false}
        title="Bonito saberlo :)"
        paragraphs={[[{ text: "Holiss, wapa,", underlined: true }], [{ text: "Hoy estoy muy feliz de saber que tus papás están ahora parcialmente al tanto de nuestras intenciones.", marked: true }], [{ text: "Estoy además muy emocionado por que, si Dios quiere, hoy regreso a Puebla acompañado de casi toda mi fam, la cual va más que dispuesta a conocerte. " }], [{ text: "Es muy bonito saber que queremos hacer las cosas bien y que lo vamos a intentar todo con la esperanza en Dios nos dará al final lo mejro para nosotros.", marked: true }], [{ text: "Qué bonito es platicar contigo a pesar de estar a casi 1,000km. " }], [{ text: "Emocionado estoy de poder verte de nuevo, justo estoy terminando de armar mi maleta y ya me siento cada vez más cerca de ti.", underlined: true }], [{ text: "Me emociona el poder platicarto todo lo que ha pasado en estas últimas semanas y poder expresarte frente a frente lo que he meditado en estos días. ", }], [{ text: "Grax por dejarme verte bien chula de bebé, bebé. Si tu dices que parecías un monito de recién nacida, yo quiero decirte que entonces eras el monito más bello, más precioso y más hermoso que alguien podría apreciar.", marked: true }], [{ text: "Te quiero tanto, bonita. Mucho mucho mucho mucho, aunque me bolquees en insta (jk).", underlined: true }], [{ text: "Nos vemos pronto, morrilla.", marked: true }], [{ text: "Con mucho cariño, Jorge V. ♥", marked: true }], [{ text: "PD: Aviso parroquial. Dado que no tendr[e compu por al menos unos 3 días, es posible que no haya actualización diaria :( Pero retomamos en cuanto mi lap esté en mis manos :) Tequieromucho ♥", underlined: true }],]}
        images={[ene5, ene5_2]} />
      <Footer />
    </div>
  )
}

export default App